# Type annotations

#dictionary

movie = {
    "name": "The Matrix",
    "year": 1999,

}

# types dictionary

from typing import TypedDict, Dict

class Movie(TypedDict):
    name: str
    year: int


movies = Movie(name="The Matrix", year="yeah")

# print(movies)


# union

from typing import Union
def square(x: Union[int, float]) -> float:
    return x*x


sq = square(3.14)

# print(sq)



# Optional

from typing import Optional

def greet(name: Optional[str]) -> None:
    if name is not None:
        print(f"Hello, {name}!")
    else:
        print("Hello, stranger!")


# greet("Alice")
# greet(None)



# state - apps memory

# node  - individual step in a graph

# graph -  collection of nodes and edges that represent a workflow or process

# edges - connections between nodes that define the flow of data or control in a graph

# conditional edges  = edges that are only followed if a certain condition is met, allowing for branching logic in the graph

# start node - the initial node in a graph where the process begins

# end node - the final node in a graph where the process concludes

# tools - specialized functions or capabilities that can be invoked by nodes in a graph to perform specific tasks or operations
# basically tools are js methods that we can call from our graph nodes to do specific things, like searching a database, calling an API, or performing calculations. They help us extend the functionality of our graph and allow us to interact with external systems or perform complex operations that aren't built into the graph itself.

# ToolNode - a node in a graph that is specifically designed to invoke a tool, allowing the graph to leverage external functions or capabilities as part of its workflow.

# StateGraph - a graph that maintains and updates a state throughout its execution, allowing for dynamic decision-making and data manipulation based on the current state of the process.

# Runnable - an interface or contract that defines a component (like a graph or node) that can be executed or run, typically with a defined input and output structure.
# can be independent, nodes use state, runnable doesnt

# Messages types
# HumanMessage - a message sent by a human user, typically containing input or instructions for the system to process.
# AIMessage - a message generated by an AI system in response to a HumanMessage, containing the system's output or response.
# SystemMessage - a message that provides context or instructions to the AI system, often used to
# FunctionMessage - a message that represents a function call or invocation, typically used to trigger specific actions or operations within the system.
# ToolMessage - a message that represents the invocation of a tool, containing information about the tool being called and any relevant parameters or data needed for its execution.


# lets create the hello world graph


# we now 